### PR TITLE
fix(discord-utilities): update regexes for 20 digit IDs

### PR DESCRIPTION
**Pull request by enxg**

### CODE REVIEW

**Review by kyranet — APPROVED** [review]

**Comment by imranbarbhuiya** [comment]
image
change it to 20 instead

**Comment by enxg** [comment]
> image change it to 20 instead

👍

**Comment by kyranet** [comment]
We're hitting 20-digit snowflakes... in 2090, though.

**Comment by enxg** [comment]
> We're hitting 20-digit snowflakes... in 2090, though.

¯\_(ツ)_/¯

**Review by favna — APPROVED** [review]

**Pull request merged**
