### PR TITLE
fix(eslint-config): disable `@typescript-eslint/no-namespace`

### PR DESCRIPTION
**Pull request by Lioness100**
(Discussed on Discord)

### CODE REVIEW

**Comment by Lioness100** [comment]
I don't know how jest snapshots work, is that something I should change manually?

**Comment by favna** [comment]
@all-contributors please add @Lioness100 for code

**Comment by favna** [comment]
screw you too allcontributors bot

**Comment by Lioness100** [comment]
Time to remove /embed-jsx 🙄🙄

**Review by favna — APPROVED** [review]

**Pull request merged**
