### PR TITLE
fix(discord.js-utilities): fixed deprecated code

### PR DESCRIPTION
**Pull request by smyalygames**
Hiya, discord.js v14.8 seems to have had some naming changes (specifically this: https://github.com/discordjs/discord.js/pull/8901/files#diff-39fa4deb1f3d44852e181492af5407ba4f3f9117372a7d3126571355e3a53cd6L87-R87), that breaks sapphire@discord.js-utilities, and I changed the names to reflect this update.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by favna — APPROVED** [review]

**Comment by smyalygames** [comment]
I'm guessing the tests failing aren't necessarily my fault? https://github.com/sapphiredev/utilities/actions/runs/4399932561/jobs/7709133722#step:7:27 as I did do a before and after test on my machine and they did seem to yield the same results.

**Comment by favna** [comment]
They aren't. It's related to codecov which is CI only. Restarted the build.

**Comment by smyalygames** [comment]
> They aren't. It's related to codecov which is CI only. Restarted the build.

Ahhh yeah, it seems all good now, thank you :)

**Comment by favna** [comment]
I'll do the release probably tomorrow somewhere during the day. Pretty busy the coming days.

**Pull request merged**
