### PR TITLE
feat: add-interaction-support-to-decorators

### PR DESCRIPTION
**Pull request by ZachHandley**
title, not like I saved the world here no need to explain more

### CODE REVIEW

**Comment by favna** [comment]
@sapphiredev pack

**Review by favna — DISMISSED** [review]

**Comment by favna** [comment]
@sapphiredev pack

**Comment by vladfrangu** [comment]
@sapphiredev pack

**Comment by vladfrangu** [comment]
@sapphiredev pack

**Comment by favna** [comment]
@sapphiredev pack

**Comment by favna** [comment]
@sapphiredev pack

**Review by favna — APPROVED** [review]

**Pull request merged**
